services:
  nordvpn:
    image: qmcgaw/gluetun:v3
    cap_add:
      - NET_ADMIN
    ports:
      - 6081:6881
      - 6081:6881/udp
      - 6011:6011
    networks:
      - vpn_proxies
    env_file:
      - ../stack.env
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=ncgKaeWGFNGLHNfpans13kTw
      - SERVER_COUNTRIES=Switzerland
      - SERVER_CATEGORIES=P2P
      - HTTPPROXY=on
      - SHADOWSOCKS=on
    restart: unless-stopped

networks:
  vpn_proxies:
    external: true