services:
  nordvpn:
    image: qmcgaw/gluetun:v3
    container_name: nordvpn_tunnel
    cap_add:
      - NET_ADMIN
    ports:
      - 6081:6881
      - 6081:6881/udp
      - 6011:6011
    env_file:
      - stack.env
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=ncgKaeWGFNGLHNfpans13kTw
      - SERVER_COUNTRIES=Switzerland
      - SERVER_CATEGORIES=P2P
    restart: unless-stopped
