name: starrs

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    environment:
      - PUID=993
      - PGID=987
      - UMASK=002
    volumes:
      - /etc/jellyfin:/config
      - /mnt/jellyfin-transcodes:/config/data/transcodes
      - /mnt/starrs/media:/data/media
    group_add:
      - "993"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`tv.adamjacobus.dev`) || Host(`thecircle.adamjacobus.dev`) && PathPrefix(`/jellyfin`)
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=990
      - PGID=987
      - UMASK=002
    volumes:
      - /etc/prowlarr:/config
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.adamjacobus.dev`) || Host(`thecircle.adamjacobus.dev`) && PathPrefix(`/prowlarr`)
      - traefik.http.routers.prowlarr.tls=true
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
    restart: unless-stopped
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=996
      - PGID=987
      - UMASK=002
    volumes:
      - /etc/radarr:/config
      - /mnt/starrs:/data
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.adamjacobus.dev`) || Host(`thecircle.adamjacobus.dev`) && PathPrefix(`/radarr`)
      - traefik.http.routers.radarr.tls=true
      - traefik.http.services.radarr.loadbalancer.server.port=7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=999
      - PGID=987
      - UMASK=002
    volumes:
      - /etc/sonarr:/config
      - /mnt/starrs:/data
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.adamjacobus.dev`) || Host(`thecircle.adamjacobus.dev`) && PathPrefix(`/sonarr`)
      - traefik.http.routers.sonarr.tls=true
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
    restart: unless-stopped
  
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    environment:
      - PUID=995
      - PGID=987
      - UMASK=002
    volumes:
      - /etc/lidarr:/config
      - /mnt/starrs:/data
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.lidarr.rule=Host(`lidarr.adamjacobus.dev`) || Host(`thecircle.adamjacobus.dev`) && PathPrefix(`/lidarr`)
      - traefik.http.routers.lidarr.tls=true
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=987
      - PGID=987
      - UMASK=002
    volumes:
      - /etc/bazarr:/config
      - /mnt/starrs/media:/data/media
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.adamjacobus.dev`) || Host(`thecircle.adamjacobus.dev`) && PathPrefix(`/bazarr`)
      - traefik.http.routers.bazarr.tls=true
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    environment:
      - PUID=988
      - PGID=987
      - UMASK=002
    volumes:
      - /etc/sabnzbd:/config
      - /mnt/starrs/usenet:/data/usenet
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.adamjacobus.dev`) || Host(`thecircle.adamjacobus.dev`) && PathPrefix(`/sabnzbd`)
      - traefik.http.routers.sabnzbd.tls=true
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    user: '985'
    environment:
      - LOG_LEVEL=debug
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyseerr.rule=Host(`epg.adamjacobus.dev`) || Host(`thecircle.adamjacobus.dev`) && PathPrefix(`/jellyseerr`)
      - traefik.http.routers.jellyseerr.tls=true
      - traefik.http.services.jellyseerr.loadbalancer.server.port=5055
      - traefik.http.middlewares.jellyseerr-stripprefix.stripprefix.prefixes=/jellyseerr
      - traefik.http.middlewares.jellyseerr-rewriterelativelocation.plugin.traefik-plugin-rewrite-response-headers.rewrites[0].header=Location
      - traefik.http.middlewares.jellyseerr-rewriterelativelocation.plugin.traefik-plugin-rewrite-response-headers.rewrites[0].regex=^/(.+)$
      - traefik.http.middlewares.jellyseerr-rewriterelativelocation.plugin.traefik-plugin-rewrite-response-headers.rewrites[0].replacement=/jellyseerr/$1

      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[0].regex=href=\"/(.+?)?\"
      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[0].replacement=href=\"/jellyseerr/$1\"
      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[1].regex=src=\"/(.+?)?\"
      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[1].replacement=src=\"/jellyseerr/$1\"

      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[2].regex=href:\"/(.*?)\"
      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[2].replacement=href:\"/jellyseerr/$1\"

      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[3].regex=\"/api/(.*?)\"
      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[3].replacement=\"/jellyseerr/api/$1\"

      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[4].regex=\"/_next/(.*?)\"
      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[4].replacement=\"/jellyseerr/_next/$1\"

      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[5].regex=\"/images/(.*?)\"
      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[5].replacement=\"/jellyseerr/images/$1\"

      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[6].regex=src:\"/(.*?)\"
      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[6].replacement=src:\"/jellyseerr/$1\"

      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[7].regex=linkUrl:\"/(.*?)\"
      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.rewrites[7].replacement=linkUrl:\"/jellyseerr/$1\"

      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.lastModified=true
      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.monitoring.types[0]=text/html
      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.monitoring.types[1]=application/javascript
      - traefik.http.middlewares.jellyseerr-rewritebody.plugin.rewrite-body.monitoring.types[2]=*/*
    volumes:
      - /etc/jellyseerr:/app/config
    restart: unless-stopped

networks:
  public:
    external: true
  vpn_proxies:
    external: true
  