services:
  traefik:
    image: traefik:2.11
    command:
      - --api.dashboard=true
      - --entrypoints.websecure.address=:443
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=public
      - --providers.docker.allowEmptyServices=true
      - --providers.file.filename=/traefik_certs.yml
      - --log.level=debug
      - --log.format=json
      - --accesslog=true
      - --accesslog.format=json
      - --accesslog.fields.names.RequestHost=keep
      - --accesslog.fields.names.RouterName=keep
    networks:
      - public
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/caddy/ssl:/ssl:ro
    restart: unless-stopped
    configs:
      - traefik_certs.yml

  cloudflared:
    image: "cloudflare/cloudflared:latest"
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    env_file:
      - ../stack.env
    networks:
      - default

networks:
  public:
    external: true

configs:
  traefik_certs.yml:
    file: certs.yml
