services:
  portainer:
    image: portainer/portainer-ce:2.19.5
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000

volumes:
  portainer_data:
